### ISSUE TITLE
Libfm compilation error

### ISSUE THREAD

**Issue by agaida** [lxde/libfm#31]
#### original reporter was Ilya87 https://github.com/lxde/pcmanfm-qt/issues/548

I use the following command line to compile libfm (master version):
./configure \ --without-gtk \ --disable-gtk-doc \ --disable-udisks \ --enable-actions \ --prefix="/usr" \ --sysconfdir="/etc" \ --disable-debug \ --disable-exif && make
build fails with error:
VALAC libfmactions_la_vala.stamp condition.vala:149.18-155.34: warning: unhandled errorGLib.Error'
condition.vala:192.8-193.40: warning: unhandled error GLib.SpawnError' action.vala:81.4-81.30: error: usenew' operator to create new objects
FileAction.from_keyfile(kf);
^^^^^^^^^^^^^^^^^^^^^^^^^^^
action.vala:144.4-144.34: error: use new' operator to create new objects FileActionMenu.from_keyfile(kf); ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ action.vala:185.28-185.31: warning: Argument 1: Cannot pass null to non-null parameter type cached_children.append(null); ^^^^ action.vala:177.8-177.82: warning: unhandled errorGLib.SpawnError'
if(Process.spawn_command_line_sync(command, out output, null, out exit_status)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
action.vala:238.21-238.24: warning: Argument 1: Cannot pass null to non-null parameter type
children.append(null);
^^^^
action.vala:334.10-334.40: warning: unhandled error GLib.KeyFileError' if(kf.load_from_file(full_path, 0)) { ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Compilation failed: 2 error(s), 6 warning(s)

vala version is 0.36.4

**Comment by agaida** [comment]
@LStranger: Would you be so kind and take care of it asap?

**Comment by tsujan** [comment]
In short, these are the errors:
```
action.vala:81.4-81.30: error: use `new' operator to create new objects
                        FileAction.from_keyfile(kf);
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
action.vala:144.4-144.34: error: use `new' operator to create new objects
                        FileActionMenu.from_keyfile(kf);
```

**Comment by mtasaka** [comment]
Already being tracked on https://github.com/lxde/libfm/pull/22 .

**Comment by tsujan** [comment]
Great! @agaida, could you merge it?

**Comment by tsujan** [comment]
It's known since Apr 7 and the fix has been there for more that 3 months!!

**Comment by agaida** [comment]
done

**Comment by drescherjm** [comment]
I just got this error in gentoo. rev 1.2.5 does not appear to have this fix.

**Comment by tsujan** [comment]
@drescherjm pcmanfm-qt doesn't depend on libfm anymore.
