### ISSUE TITLE
"XDG_TEMPLATES_DIR is set to invalid path" warning is too noisy

### ISSUE THREAD

**Issue by jleclanche** [lxde/libfm#33]
From here:

https://github.com/lxde/libfm/blob/5d03c2d8dc5570e31d5a65c3b8fac97d5755fd36/src/base/fm-templates.c#L824

This seems to trigger every single time I open any libfm app, even if I properly set the variable.

Googling the warning, it's all over the place in every single pcmanfm startup log etc. Something seems wrong. I'm not sure it ever even worked? Either way, the warning should either be fixed, take a default or go away...

**Comment by yan12125** [comment]
As a workaround, I modify ```~/.config/user-dirs.dirs```
```Diff
--- /home/yen/.config/user-dirs.dirs.orig       2017-11-08 22:19:34.022490006 +0800
+++ /home/yen/.config/user-dirs.dirs    2017-11-08 22:19:40.998958987 +0800
@@ -7,7 +7,7 @@
 # 
 XDG_DESKTOP_DIR="$HOME/Documents"
 XDG_DOWNLOAD_DIR="$HOME/Documents"
-XDG_TEMPLATES_DIR="$HOME/"
+XDG_TEMPLATES_DIR="$HOME/Documents"
 XDG_PUBLICSHARE_DIR="$HOME/"
 XDG_DOCUMENTS_DIR="$HOME/Documents"
 XDG_MUSIC_DIR="$HOME/"
```
Of course ~/Documents should be created beforehand.

**Comment by ib** [comment]
@jleclanche Is the problem still present? If so, what is XDG_TEMPLATES_DIR set to?

**Comment by arteze** [comment]
I have this problem, but with /root

**Comment by ib** [comment]
XDG_TEMPLATES_DIR must not be set to the user's home or the root directory.

**Comment by arteze** [comment]
@ib I don't know why the issue was closed, I want to clarify that I have that problem with root, unlike the problem that the person who started the issue had, which is without root.

And what is the solution to the problem?

I don't understand, does XDG_TEMPLATES_DIR have to have some value? How is it assigned?

If we can't assign the value to it, pcmanfm should not show the warning.

**Comment by arteze** [comment]
The problem in my case, for some unknown reason, has already been solved.

I'm using _pcmanfm_ on _PuppyLinux_, where the default is to be superuser.

If I run the following command to see if pcmanfm reads the file `/root/.config/user-dirs.dirs`, there is no response, it is as if it did not read it, which seems strange to me.

```sh
strace -f pcmanfm /root 2>&1 | grep -i user-dirs.dirs
```

If I run the command `xdg-user-dirs-update` that appears in the file, it changes it back, so I wouldn't have to run it.
```sh
xdg-user-dirs-update
/root/DOCUMENTS was removed, reassigning DOCUMENTS to homedir
```
