### ISSUE TITLE
Unable to launch X11 programs on Wayland

### ISSUE THREAD

**Issue by ascent12** [lxde/libfm#40]
When you're trying to launch a program, DISPLAY is incorrectly getting set to "wayland-0", which is supposed to be for WAYLAND_DISPLAY.
So any X11 programs that get launched would fail to open the X11 display (with Xwayland) and exit.

The offending lines would be:
https://github.com/lxde/libfm/blob/9ce974e49ca0a6143174e607550c05f863e1c356/src/base/fm-action.c#L734-L736
https://github.com/lxde/libfm/blob/9ce974e49ca0a6143174e607550c05f863e1c356/src/base/fm-action.c#L671

I'm not sure what the purpose of setting DISPLAY like this is, but it seems like `g_app_launch_context_get_display` is returning WAYLAND_DISPLAY in a wayland session.

**Comment by ib** [comment]
An attempt was made to fix this in #62. The fix is incorrect.

**Comment by ib** [comment]
Should be fixed now.
