### ISSUE TITLE
PcManFM not recognizing st (suckless's simple terminal)

### ISSUE THREAD

**Issue by Luke100pro** [lxde/libfm#51]
I was just bugfixing the xsession, and i can not do anything about this.

.xsession-errors output
`** (pcmanfm:638): WARNING **: 13:34:20.238: terminal st isn't known, consider report it to LibFM developers`

Please, add this terminal.

**Comment by LStranger** [comment]
Thank you very much for reporting this.
Your help would be much appreciated. Two things are needed:
1) manual page (options to execute a command in terminal and to not close a window after finishing the execution are in interest);
2) if there is a .desktop file available.

**Comment by bbidulock** [comment]
There is a manual page here: [st.1.gz](https://github.com/lxde/libfm/files/4248016/st.1.gz)
