### ISSUE TITLE
PCManFM not recognizing germinal

### ISSUE THREAD

**Issue by julientechdev** [lxde/libfm#52]
I've been using Germinal for a while now, it's an ultra simple VTE-based terminal:
https://github.com/Keruspe/Germinal

One can configure the startup command to be any shell or program, default is tmux but I just have zsh.

The main reason I'm creating this issue is because I cannot use the "open this folder in terminal" feature by pressing F4, it justs open a terminal to my $HOME.

Here's the warning message:
`** (pcmanfm:4380): WARNING **: 01:00:33.762: terminal germinal isn't known, consider report it to LibFM developers`

I can help if needed.

**Comment by LStranger** [comment]
Thank you very much for reporting this.
Your help would be much appreciated. Two things are needed:
1) manual page (options to execute a command in terminal and to not close a window after finishing the execution are in interest);
2) if there is a .desktop file available.

From your link it seems `-e` is used to execute, no option to not close, and .desktop file seems to be `org.gnome.Germinal.desktop`. Is that correct?

**Comment by avrelaun** [comment]
1. There is no manual page, and I've already looked into options to execute a command in terminal. Germinal is just a wrapper for VTE, and has an option to send the default command to execute, the default being `tmux` but I configured mine to be `zsh`.
2. Yes, `https://github.com/Keruspe/Germinal`, containing `Exec=/usr/bin/germinal`
