### ISSUE TITLE
Untitled filter in chooser

### ISSUE THREAD

**Issue by Survolog** [lxde/libfm#92]
https://github.com/lxde/libfm/blob/695d3e863440b50c50c53ff7287b24b42a624a9e/src/gtk/fm-app-chooser-dlg.c#L234
Hello.
Maybe
`-    file = fm_select_file(GTK_WINDOW(data->dlg), NULL, "/usr/bin", TRUE, FALSE, filter, NULL);`
`+    file = fm_select_file(GTK_WINDOW(data->dlg), NULL, "/usr/bin", TRUE, FALSE, NULL, NULL);`
for hide "Untitled filter"?

Thanks!

**Comment by ib** [comment]
Fixed.
